name: han
description: Een app voor de HAN
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  google_fonts: ^2.1.0
  provider: ^6.0.1
  mobx: ^2.0.6
  flutter_mobx: ^2.0.3+1
  intl: ^0.17.0
  xedule_api:
    path: packages/xedule_api
  xedule_repository:
    path: packages/xedule_repository
  flutter_svg: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.5+1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding/
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-VariableFont_wght.ttf