name: xedule_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter_inappwebview: ^5.3.2
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  xedule_api:
    path: ../xedule_api

dev_dependencies:
  build_runner: ^2.1.2

