name: xedule_api
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_serializable: ^6.1.3
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.1.2
